server:
  port: 8080

alipay:
  # 支付宝应用 ID
  appId: 9021000154686515
  # 应用私钥
  appPrivateKey: ******
  # 支付宝公钥
  alipayPublicKey: ********
  # 回调接口地址（公网地址 + 接口 URI）
  # 先跟着写，后面代码写完就明白了，公网地址换成自己的穿透地址
  notifyUrl: http://qa6cd82c.natappfree.cc/alipay/notify
